shell = "zsh"

[plugins.atuin]
local = "~/.config/sheldon/local"

[plugins.eza]
local = "~/.config/sheldon/local"

[plugins.fzf]
local = "~/.config/sheldon/local"

[plugins.mise]
local = "~/.config/sheldon/local"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.pure]
github = "sindresorhus/pure"
use = ["async.zsh", "pure.zsh"]
