shell = "zsh"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.completion]
github = "sorin-ionescu/prezto"
dir = "modules/completion"
use = ['init.zsh']

[plugins.local]
local = "~/.config/sheldon/local"
use = ["{init,path,alias,history}.zsh"]
