[colors]
background = "#241B2F"
foreground = "#F1F1F1"

selection-background = "#3A2A4B"
selection-foreground = "#F1F1F1"

cursor = "#F92AAD"
vi-cursor = "#36F9F6"

tabs = "#2E2144"
tabs-active = "#F92AAD"
tabs-active-foreground = "#191621"
tabs-active-highlight = "#36F9F6"
bar = "#191621"
split = "#3A2A4B"

black = "#382C4D"
red = "#FE4450"
green = "#72F1B8"
yellow = "#FEDE5D"
blue = "#34D3FB"
magenta = "#F92AAD"
cyan = "#36F9F6"
white = "#F2EBE0"

light-black = "#7B6A98"
light-red = "#FF7D86"
light-green = "#C6FFE5"
light-yellow = "#FFF0B4"
light-blue = "#AAEEFF"
light-magenta = "#FFA8DF"
light-cyan = "#9EFFFD"
light-white = "#F1F1F1"

dim-foreground = "#CFC8E4"
dim-black = "#2B203D"
dim-red = "#C33B47"
dim-green = "#58CFA0"
dim-yellow = "#CCBE58"
dim-blue = "#2AA7C7"
dim-magenta = "#C971C0"
dim-cyan = "#2ED2D0"
dim-white = "#D9D3C6"

search-match-background = "#433055"
search-match-foreground = "#F1F1F1"
search-focused-match-background = "#F92AAD"
search-focused-match-foreground = "#191621"
