padding-x = 20
padding-y = [0, 0]
theme = "synthwave_84"

[window]
opacity = 0.8
decorations = "Transparent"
blur = true
macos-use-unified-titlebar = true

[fonts]
family = "Juisee NF"
size = 14.0

[cursor]
shape = "underline"
blinking = true
blinking-interval = 750

[title]
content = ""
