padding-x = 10
padding-y = [10, 0]
theme = "synthwave_84"
line-height = 1.1

[window]
opacity = 0.8
decorations = "Transparent"
blur = true

[fonts]
family = "Juisee NF"
size = 15

[cursor]
shape = "beam"
blinking = true
blinking-interval = 750
